# Generated by Django 4.2.7 on 2023-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoename', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('detail', models.CharField(max_length=100)),
                ('cat', models.IntegerField(choices=[(1, 'Men'), (2, 'Women'), (3, 'Child')])),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
