# Generated by Django 4.2.7 on 2024-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0005_shoesproduct_subcat_alter_shoesproduct_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shoesproduct',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shoesproduct',
            name='subcat',
            field=models.IntegerField(choices=[(1, 'All'), (2, 'athletic'), (3, 'casual'), (4, 'boots'), (5, 'sandals'), (6, 'formal'), (7, 'slippers')], default=1),
        ),
    ]
