# Generated by Django 4.2.7 on 2024-01-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0006_cart_total_price_alter_shoesproduct_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
