# Generated by Django 4.2.7 on 2024-01-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0007_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
