# Generated by Django 4.2.7 on 2024-01-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0008_remove_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
