# Generated by Django 4.2.7 on 2024-01-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0009_cart_tprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tprice',
            field=models.IntegerField(),
        ),
    ]
