# Generated by Django 4.2.7 on 2024-01-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0014_placeorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='pid',
        ),
    ]
