# Generated by Django 4.2.7 on 2024-01-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0015_remove_placeorder_pid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
