# Generated by Django 4.2.7 on 2024-01-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0016_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='footapp.shoesproduct'),
            preserve_default=False,
        ),
    ]
