# Generated by Django 4.2.7 on 2024-01-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0017_placeorder_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
