# Generated by Django 4.2.7 on 2024-01-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0018_placeorder_quantity_alter_placeorder_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='footapp.placeorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footapp.shoesproduct')),
            ],
        ),
    ]
