# Generated by Django 4.2.7 on 2024-01-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0020_placeorder_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='pid',
        ),
    ]
